//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectoLibre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Heroe
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string habilidad { get; set; }
        public string imagenName { get; set; }
        public byte[] imagenData { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
    }
}
